import type { Metadata } from 'next'
import './globals.scss'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode,
  modal: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body>
      <Navbar type="default" />
      <main>
        {children}
        {modal}
        </main>
      <Footer />
      </body>
    </html>
  )
}
